# Generated by Django 3.2.7 on 2021-11-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userimages_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
