# Generated by Django 3.2.7 on 2021-11-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userimages_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
