# Generated by Django 3.2.7 on 2021-11-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211120_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
