# Generated by Django 3.2.7 on 2021-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20211120_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
