# Generated by Django 3.2.7 on 2021-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userprofile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tree_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
