# Generated by Django 3.2.7 on 2021-11-26 09:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20211125_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
    ]
