# Generated by Django 3.2.7 on 2021-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=254, null=True)),
                ('sub_display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('sub_display_description', models.CharField(blank=True, max_length=254, null=True)),
                ('sub_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_images', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
