# Generated by Django 3.2.7 on 2021-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20211121_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolly',
            name='sub_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
