# Generated by Django 3.2.7 on 2021-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_trolly_sub_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolly',
            name='credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
