# Generated by Django 3.2.7 on 2021-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20211028_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
