# Generated by Django 3.2.7 on 2021-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_trolly_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_display_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
