# Generated by Django 3.2.7 on 2021-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_subscription_sub_display_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
