# Generated by Django 3.2.7 on 2021-11-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_order_sales_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
