# Generated by Django 3.2.7 on 2021-11-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(default=1, editable=False, max_length=32)),
                ('request_name', models.CharField(max_length=50)),
                ('request_email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=25)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('availability_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(default='No image', max_length=25)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.category')),
            ],
        ),
    ]
