# Generated by Django 3.2.7 on 2021-11-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='image',
            field=models.CharField(default='No image', max_length=25),
        ),
    ]
