# Generated by Django 3.2.7 on 2021-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmeto', '0002_alter_requestimage_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='request_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
