# Generated by Django 3.2.7 on 2021-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmeto', '0003_alter_requestimage_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='site_owner_message',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
